ConsenSys/qubernetes

- README.md
Minikube has been migrated from Homebrew Cask to Homebrew Core. The instructions on the official website (also linked) have made the same change.
> Update Minikube install instruction

- .github/actions/qube-gen-k8s/Dockerfile
- .github/actions/qube-gen-k8s/action.yaml
- .github/actions/qube-gen-k8s/entrypoint.sh
- .github/workflows/7nodes-test.yaml
Adding github actions and workflow to test the generation of the
7nodes examples, uses the public qubernetes docker image for
generating the resources and tests the generation of the k8s yaml
which is then run on a k8s service (kind).
Triggered  when a commit is pushed, or PR to master is opened.
> Adding github actions and workflow.

- templates/quorum/genesis.json.erb
Adding `"homesteadBlock": 0,  "maxCodeSize": 35,` to genesis.json.erb
template (genesis.json up to Quorum version 2.2.5). 
The `homesteadBlock` wasn't being set in the genesis for 2.2.5 (1.8 geth), and this didn't cause any issues, but when testing against the upgrade geth 1.9.7 PR for quorum, the fact that the homesteadBlock wasn't being set caused `Error: exceeds block gas limit` when trying to deploy contracts, and a  "Consensus not specified" error when running IBFT
Adding it here as it should be set for Quorum 2.2.5.
> Add homesteadBlock and maxCodeSize to genesis.

- README.md
Host webm files on the gitHub pages for qubernetes, instead of from personal github account.
> Host webm files on gitHub pages for qubernetes.

- examples/config/qubernetes-ingress.yaml
- qubernetes
- templates/k8s/quorum-ingress.yaml.erb
- templates/k8s/quorum-services.yaml.erb
Add the ability to generate ingress resources, either
OneToOne where a k8s ingress resource is created for each
node (1:1), or OneToMany (1:N) where one ingress resource is created
for all quorum  nodes deployed in the cluster, and all nodes share a
common host name.
Currently only support one host FQDN per ingress.
Only exposing the geth rpc endpoint.
Not supporting tls at this time, however tls can be added with
self signed certificate (which would requires modification of the
geth client) or using a valid root CA.
> Add ability to generate ingress resources.

- examples/config/qubernetes-custom-docker-repo.yaml
- templates/k8s/quorum-deployment.yaml.erb
Add an optional `Docker_Repo` yaml entry for each container (Transaction Manager, quorum),
to the minimal config. This allows the user to configure the docker repo that the containers should be pulled from, e.g. their dev containers, internal repos, etc. If not set, the containers will be pulled from the official quorum docker hub repo: https://hub.docker.com/u/quorumengineering/.
> Make the docker repo optionally configurable.

- examples/config/qubernetes-network-policy.yaml
- qubernetes
- templates/k8s/network-policy.yaml.erb
If `NetworkPolicy: true` set in the minimal config, generate a k8s network policy for the quorum network / namespace to allow traffic in / out on the specified ports (RPC, Raft, TM, P2P).
> Add network policy generation capability.

- examples/config/qubernetes-pvc-annotations.yaml
- examples/config/qubernetes-pvc-storageclass.yaml
- templates/k8s/persistent-volumes.yaml.erb
- templates/k8s/quorum-deployment.yaml.erb
- Added optional annotations on PVC.
- Added optional storageClassName for PVCs to config.
- (clean up) Removed dead code in `quorum-deployment.yaml.erb` which was left over from when `hostPath` was support. `hostPath` is no longer supported as a storage option, so remove logic around it.
---
*  Added optional storageClassName for PVCs to config.
Allow the config to specific the storageClassName to use with the
PVC, currently both `storageClassName` and the annotation `volume.beta.kubernetes.io/storage-class` are supported, but the annotation `volume.beta.kubernetes.io/storage-class` won't be supported by Kubernetes in the future
see: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
An example of using `storageClassName` in the config file has been …
> Add optional annotations & storageclass to PVCs.

- contracts/runscript.sh
- examples/config/qubernetes-security-context.yaml
- helpers/container/geth-attach.sh
- helpers/container/geth-exec.sh
- templates/k8s/quorum-deployment.yaml.erb
* If the k8s securityContext is set in the config add it to the deployments, at the top level.
see an example: examples/config/qubernetes-security-context.yaml
ks:
securityContext:
runAsUser: 430
...
note: not supporting the additions of capabilities at this time.
note: not supporting pod level overriding securityContext at this time.
* add --datadir to all geth attach commands, as if the securitycontext is set limiting the user's privileges. e.g. non root,   --datadir is required or else the following error will be seen:
Fatal: Failed to start the JavaScript console: mkdir /.ethereum: permission denied
> Add support for k8s securityContext on deployments.

- Dockerfile
- docker-build.sh
When building docker images (from a git tag) to be pushed to docker hub, certain docker image labels should be set to help with integrity, clarity, self documenting, etc. adding a helper script (docker-build.sh) which sets and passes in the label and env vars, e.g. VERSION (tag),
COMMIT_SHA of the image was built from.
Following OCI spec: https://github.com/opencontainers/image-spec/blob/master/annotations.md
> Adding docker image labels and build helper script.

- examples/config/qubes-minimal.yaml
- qubernetes
- quorum-config
- quorum-keygen
- templates/k8s/network-policy.yaml.erb
- templates/k8s/persistent-volumes.yaml.erb
- templates/k8s/quorum-deployment.yaml.erb
- templates/k8s/quorum-genesis-config.yaml.erb
- templates/k8s/quorum-ingress.yaml.erb
- templates/k8s/quorum-keystore.yaml.erb
- templates/k8s/quorum-services.yaml.erb
- templates/k8s/quorum-shared-config.yaml.erb
- templates/quorum/gen-keys.sh.erb
- templates/quorum/genesis.json.erb
- templates/quorum/permissioned-nodes.json.erb
- templates/quorum/tessera-config-9.0.json.erb
- templates/quorum/tessera-config-enhanced.json.erb
- templates/quorum/tessera-config.json.erb
The entries required by the base config have been reduced to: nodes.number, consensus, quorum version, and tessera version.  An example of the minimal config is added under `examples/config/qubes-minimal.yaml` and shown here: 
```
nodes:
number: 4
quorum:
consensus: istanbul
quorum:
Quorum_Version: 2.2.5
tm:
Name: tessera
Tm_Version: 0.11
```
All other values will receive reasonable defaults, e.g. geth ports will be the default geth ports. The default values are as follows: 
```
Raft_Port = 50401
Tm_Port = 9001
Node_RPCPort = 8545
geth p2p port = 30303
service.type =  "NodePort"
geth.verbosity = 9
geth.chainId = 1101
Tessera_Config_Dir = "out/config"   
Genesis_File = "out/config/genesis.json"
Permissioned_Nodes_File = "out/config/permissioned-nodes.json"
Key_Dir_Base = "out/config" …
```
> Reduce required config values by setting reasonable defaults.

- quickest-start.sh
* In `quickest-start.sh`, check the OS and whether `kind` and `kubectl` are installed, if not install them for OS.
* Support for linux-gnu and mac-os.
* Add additional commands that user can run from outside the container, e.g. geth-exec, helpers/run_contracts.sh
> Install kind, kubectl in quickest-start.sh (Mac,Linux).

- 7nodes/istanbul-7nodes-constellation/qubernetes-istanbul-constellation-7nodes-pvc.yaml
- 7nodes/istanbul-7nodes-tessera/qubernetes-istanbul-tessera-7nodes-pvc.yaml
- 7nodes/raft-7nodes-constellation/qubernetes-raft-constellation-7nodes-pvc.yaml
- 7nodes/raft-7nodes-tessera/qubernetes-raft-tessera-7nodes-pvc.yaml
- examples/config/qubernetes-ingress-ws.yaml
- qubernetes
- templates/k8s/network-policy.yaml.erb
- templates/k8s/quorum-deployment.yaml.erb
- templates/k8s/quorum-ingress.yaml.erb
- templates/k8s/quorum-services.yaml.erb
Add support for connecting to geth via websockets rpc. The default port is set to `8546` and will always be set, but in order to use websockets they need to be enabled in the `geth.Geth_Startup_Param` inside the config yaml, e.g. --ws --wsorigins=\"*\" --wsaddr 0.0.0.0 see examples/config/qubernetes-ingress-ws.yaml
To override the default set it in the config under `geth.Node_WSPort`.
note:
If trying to connect externally via an ingress be aware that depending on the backend k8s service and how the load balancing is implemented the health checks may fail, e.g. for GKE currently has a health check that uses http, and setting a configurable health check in k8s is not supported yet,
but will be available soon: https://github.com/kubernetes/ingress-gce/issues/1067.
> Add support geth websockets rcp.

- helpers/add_nodes_to_k8s.sh
- helpers/ibft_add_nodes_to_k8s.sh
- helpers/raft_add_existing_update.sh
* when running `add_nodes_to_k8s.sh` or `ibft_add_nodes_to_k8s.sh` add all the updated config
files execpt the genesis config.
* `kubectl exec [POD]` --> `kubectl exec [POD] --` as the previous syntax is deprecated
> Minor fixes for adding (raft/ibft) nodes.

- templates/k8s/quorum-deployment.yaml.erb
- templates/quorum/genesis.json.erb
* generate genesis.json to work for 2.6.0.
* add --allow-insecure-unlock flag to geth startup params.
> Support quorum 2.6.0.

- testing/qversions-config/qubes-ibft-2.2.0.yaml
- testing/qversions-config/qubes-ibft-2.3.0.yaml
- testing/qversions-config/qubes-ibft-2.4.0.yaml
- testing/qversions-config/qubes-ibft-2.5.0.yaml
- testing/qversions-config/qubes-ibft-2.6.0.yaml
- testing/qversions-config/qubes-raft-2.2.0.yaml
- testing/qversions-config/qubes-raft-2.3.0.yaml
- testing/qversions-config/qubes-raft-2.4.0.yaml
- testing/qversions-config/qubes-raft-2.5.0.yaml
- testing/qversions-config/qubes-raft-2.6.0.yaml
- testing/test-k8s-resources.sh
- testing/test-qnet.sh
* add config for all supported version of quorum to run `./test.sh qversions`.
* minor fixes / augmentations for test scripts, e.g. support '.' in file names of configs for testing.
> Add tests for supported versions of quorum.

- README.md
- qube-init
- quickest-start.sh
- quorum-init
- testing/gen-configs.sh
separates quorum-init into 2 scripts...
-quorum-init only generates resources needed for quorum
-qube-init calls quorum-init and generates kubernetes resources
updates calls to quorum-init in readme/tests
adds action flag (--action create|update, --action=create|update, -acreate|update) to skip user prompt of asking about out directory, not having flag will run prompt if out directory exists
example of how to run with flags:
./quorum-init --action=create qubernetes.yaml
./quorum-init --action=update qubernetes.yaml
./qube-init --action=create qubernetes.yaml
./qube-init --action=update qubernetes.yaml
> Refactor quorum-init script

- examples/config/qubernetes-custom-docker-repo.yaml
- examples/config/qubernetes-ingress.yaml
- examples/config/qubernetes-istanbul-7nodes.yaml
- examples/config/qubernetes-istanbul-generate-8nodes.yaml
- examples/config/qubernetes-network-policy.yaml
- examples/config/qubernetes-pvc-annotations.yaml
- examples/config/qubernetes-pvc-storageclass.yaml
- examples/config/qubernetes-raft-generate-8nodes.yaml
- examples/config/qubernetes-security-context.yaml
- qubernetes
- qubernetes.yaml
- quorum-config
- templates/k8s/network-policy.yaml.erb
- templates/k8s/quorum-ingress.yaml.erb
- templates/k8s/quorum-services.yaml.erb
- templates/quorum/tessera-config-9.0.json.erb
- templates/quorum/tessera-config-enhanced.json.erb
adds cors to tessera config for 3rd party port
allows remix to connect to tessera for private key info
makes tessera 3rd party port configurable
fixes quorum p2p typos
> enable cors on tessera 3rd party

- examples/config/qubernetes-ingress-ws.yaml
- templates/k8s/quorum-ingress.yaml.erb
Websock ingress are not fully supported out of the box by various K8s services, and users may not want to add ws geth ingresses. When enabling K8s ingresses do not geth ws by default, but allow ws be enabled in the config.
service:
Ingress:
ws: true
> Make geth ws ingress optional.

- templates/k8s/quorum-deployment.yaml.erb
Check for the existence of the geth.ipc before considering the quorum container to be in a ready state.
> Add K8s readinessProbe to quorum container.

- 7nodes/istanbul-7nodes-constellation/qubernetes-istanbul-constellation-7nodes-pvc.yaml
- 7nodes/istanbul-7nodes-tessera/qubernetes-istanbul-tessera-7nodes-pvc.yaml
- 7nodes/raft-7nodes-constellation/qubernetes-raft-constellation-7nodes-pvc.yaml
- 7nodes/raft-7nodes-tessera/qubernetes-raft-tessera-7nodes-pvc.yaml
- examples/config/qubernetes-custom-docker-repo.yaml
- examples/config/qubernetes-ingress-ws.yaml
- examples/config/qubernetes-ingress.yaml
- examples/config/qubernetes-istanbul-7nodes.yaml
- examples/config/qubernetes-istanbul-generate-8nodes.yaml
- examples/config/qubernetes-network-policy.yaml
- examples/config/qubernetes-pvc-annotations.yaml
- examples/config/qubernetes-pvc-storageclass.yaml
- examples/config/qubernetes-raft-generate-8nodes.yaml
- examples/config/qubernetes-security-context.yaml
- examples/config/qubes-minimal.yaml
- qube-init
- qubernetes
- qubernetes.yaml
- templates/k8s/persistent-volumes.yaml.erb
- templates/k8s/quorum-deployment.yaml.erb
- templates/k8s/quorum-genesis-config.yaml.erb
- templates/k8s/quorum-ingress.yaml.erb
- templates/k8s/quorum-services.yaml.erb
- templates/k8s/quorum-shared-config.yaml.erb
- templates/quorum/genesis.json.erb
* `quorum` config (key/values) are now separate from the k8s keys/values in the config, ingress, services, namespace, etc. live under their own yaml key `k8s:`
* update 7node configs to reflect changes.
* update example configs to reflect changes.
>  Reorg config to separate quorum config from k8s.

- examples/config/qubernetes-monitor.yaml
- qubernetes
- templates/k8s/monitor.yaml.erb
- templates/k8s/quorum-deployment.yaml.erb
- templates/k8s/quorum-services.yaml.erb
- templates/k8s/quorum-shared-config.yaml.erb
- templates/monitor/prometheus.yml.erb
* optionally allow enabling prometheus monitoring of geth.
* if monitoring is enabled, start geth with the metric / monitoring params and create k8s deployment for prometheus server that 
connect to geth monitoring/metrics endpoints.
* allow for a configureable nodeport for the prometheus server deployment service.
> Add support for prometheus geth monitoring.

- examples/config/qube-storageclass.yaml
- qubernetes
- templates/k8s/persistent-volumes.yaml.erb
- templates/k8s/storage-classes/eks-storage-class.yaml.erb
This is necessary for some k8s runtimes, e.g. EKS. See examples/config/qube-storageclass.yaml.
Templates for custom storageClasses should be placed under `templates/k8s/storage-classes`.
> Add support for custom k8s storageClass.

- templates/quorum/genesis.json.erb
* Use the ethkey cmd in genesis template to obtain the account from the json key file when setting the initial account allocations in the genesis.json.
> Fix genesis inital account allocations.

- templates/k8s/persistent-volumes.yaml.erb
- templates/k8s/quorum-deployment.yaml.erb
Previously there were 3 PVC per node: logs, tm and quorum, this changes that to one PVC per node with subPaths for logs, tm and quorum.
> K8s PVC changed to one per node.

- testing/test-qnet.sh
* Both containers (tm and quorum) should be in a ready state when testing networks, this is set by the readinessProbes.
> Check READY state for both containers when testing.

- qube-init
- quorum-config
- quorum-init
- templates/quorum/genesis.json.erb
- templates/quorum/istanbul-validator.toml.erb
* Allow ./quorum-config to accept the --action=update flag, if the
action is update, do not regenerate the genesis.json, as the
genesis.json should only be create when initializing a new network.
* Move istanbul-validator.toml to its own generator file, instead of creating 
it inside the genesis generator.
> Do not regenerate genesis.json if action=update.

- qubernetes
- templates/k8s/quorum-deployment.yaml.erb
Allow for setting the full repo + name of the quorum image. This is
useful for local dev, e.g. skaffold.
Set `Docker_Repo_Full` in the node config.
> Allow docker full repo & image setting.

- qctl/networkcmd.go
- qctl/nodecmd.go
- qctl/qctl.go
- qctl/utils.go
Adding the optional `--wait` flag to `qctl deploy network` will query the network being deploy to K8s and wait for all pods
to become healthy before exiting.
`qctl deploy network --wait`
* Support displaying geth startup params for node(s). 
`qctl ls nodes --gethparams`
>  Support `--wait` flag when deploying network.

- qctl/qctl.go
- qctl/testcmd.go
* add support to `qctl` to run test contract, e.g. as in
`helpers/run_contract.sh`, runs the test contract (private | public) that
is setup on the node.
`qctl test contract quorum-node1`
> Add qctl support for basic contract test.

- qubernetes
* When generating the K8s deployment files, prefix the files with the
unique node name, this helps with management / keeping the files in sync
with a running network, as the deployment files can be easily found via
the unique node name.
> Prefix K8s deployment files with the uniq node name.

- qctl/configcmd.go
- qctl/configyaml.go
- qctl/srvcmd.go
- qctl/utils.go
* `qctl init --monitor` to enable prometheus support for geth / quorum.
> [qctl] add geth prometheus support.

- qctl/nodecmd.go
- qctl/qctl.go
When deleting a node, remove the associated k8s deployment, pvc,  and service. If the
`--hard` flag is set, remove the associated keys and configs for the
node. `qctl delete node` always removes the node from the config
file.
* `qctl delete node  NODENAME``
* `qctl delete node --hard NODENAME`` // also remove the associated
keys.
> [qctl] support deleting a node.

- qctl/local-dev/Dockerfile.gethbase
- qctl/local-dev/Dockerfile.gethonly
- qctl/local-dev/README.md
* include separated Dockerfile for making subsequent builds faster,
these are simply the core geth/quorum Dockerfile broken into 2 parts.
* describe the flow of building a quorum container locally including any
changes made the the code.
* describe deploying a mixed quorum network of different version
including a local Quorum build (2.7.0, 2.6.0, quorum-local).
> [qctl] Add documentation for the local dev flow.

- qctl/nodecmd.go
- qctl/qctl.go
- qctl/testcmd.go
Stopping a node will remove the node from the running K8s deployment,
but will not remove any other K8s resources or on disk resources, e.g.
the persisted state will be kept (PVC), as well as the keys, etc.
To "restart" the node, run `qctl create network` which will redeploy the
K8s deployment.
> [qctl] add `qctl stop node NODE_NAME`.

- qctl/builds/build-binaries.sh
- qctl/go.mod
- qctl/go.sum
Build qctl binaries for main os architectures using gox:
-osarch="linux/amd64 linux/386 darwin/amd64 darwin/386 windows/amd64 windows/386"
https://github.com/mitchellh/gox
The binaries should be build and attached to the next release.
> [qctl] build script for binaries for various os archs.

- qctl/README.md
- qctl/acceptancetestyaml.go
- qctl/nodecmd.go
- qctl/qctl.go
- qctl/testcmd.go
Add support for running acceptance tests against a running network:
qctl test accepttest --node-ip={K8S_NODEIP}
Requires the node-ip of the running K8s deployment. To overwrite the
default tags, use the --tags flags and explicitly set the acceptance
test tags to run. The tags have defaults depending on the consensus of
the network:
raft: "(basic || basic-raft || networks/typical::raft) && !extension"
ibft: "(basic || basic-istanbul || networks/typical::istanbul) && !extension"
Update README.md
> [qctl] add support for acceptance tests.

- qctl/nodecmd.go
* support updating the consensus, quorumVersion, tmVersion, and
txManger.
qctl update node --name=NODE_NAME --qversion=2.6.0 --tmVersion=0.10.4
> [qctl] support more flags for qctl update node.

- qctl/configcmd.go
- qctl/configyaml.go
- qctl/testcmd.go
when writing files to disk, e.g. config, accept test config, if there is
an error log it and error out.
> [qctl] check errors when writing files.

- qctl/configcmd.go
- qctl/configyaml.go
- qctl/nodecmd.go
- qubernetes
- templates/k8s/quorum-deployment.yaml.erb
* in base k8s templates for deployments, allow the full transaction
manager image to be set, for example when using a local image.
* [qctl] allow for init, add, updating and displaying of transaction
manager full image.
> Allow setting of full image for transaction manger.

- qctl/go.mod
- qctl/go.sum
- qctl/srvcmd.go
- qctl/testcmd.go
- qctl/utils.go
* The quorum services to list should be obtained from the config being
used. Show auxiliary services (cakeshop, monitoring) first, then all
quroum node services.
* if --node flags are set, only show the serivces that are both in the
config and requested with a --node flag.
> [qctl] when listing urls get services from config.

- qctl/networkcmd.go
- qctl/testcmd.go
- qctl/utils.go
When running generate network, and acceptance test, containers are used
(qubernetes and acctests), if docker returns an error, log the error and
fail with an exit code > 0.
> [qctl] check for docker errors.

- qctl/README.md
- qctl/nodecmd.go
when the node name is required for node commands, make it a required
argument instead of a `--name` flag, as this is more consistent.
> qctl add node [flags] NodeName
> qctl update node [flags] NodeName
> qctl ls node [flags] NodeName
> [qctl] when node name required make it an arg.

- qctl/scripts/addraftnode.sh
- qctl/scripts/deleteraftnode.sh
- qctl/scripts/rmraftid.sh
Currently, adding and removing raft nodes includes running
'raft.addPeer(enode)' on the running cluster and
'raft.removePeer(raftId)' script the flow for adding and removing raft
nodes to a running quorum cluster.
./addraftnode.sh quorum-node5
./deleteraftnode.sh quorum-node5
> [qctl] helper scripts for add/remove raft nodes.

- quorum-keygen
- templates/k8s/quorum-keystore.yaml.erb
- templates/quorum/gen-keys.sh.erb
When generating the nodekey address persist it, and set it in a configmap,
this is useful for cross cluster info as this is public and needs to be
shared when there is a cross cluster IBFT network.
> save and set nodekey address in a configMap

- qctl/cakeshop.go
- qctl/configcmd.go
- qctl/monitor.go
- qctl/networkcmd.go
- qctl/nodecmd.go
- qctl/testcmd.go
- qctl/utils.go
runCmd returns the error from executing the command instead of log.Fatal
and erroring out internally, so that the callers of the function can
handle the error as they like.
> [qctl] runCmd return error.

- qctl/srvcmd.go
- qctl/utils.go
qctl ls urls --type nodeport --p2p
This is useful for multi-cluster as a reachable p2p URL needs to be
easily obtained.
> [qctl] support listing (nodeport) p2p url.

- qctl/nodecmd.go
- quorum-config
- quorum-init
- templates/quorum/istanbul-validator.toml.erb
- templates/quorum/permissioned-nodes.json.erb
- templates/quorum/tessera-config-9.0.json.erb
- templates/quorum/tessera-config-enhanced.json.erb
- templates/quorum/tessera-config.json.erb
Initial support for running a quorum k8s network across multiple clusters.
To run a multi-cluster Quorum k8s network, a quorum network must initially be started in a single cluster and the `genesis.json` needs to be shared with all other cluster that wish to connect. 
There is a new (optional) entry in the qubernetes config `external-nodes`, e.g.
```
external_nodes:
- Node_UserIdent:  quorum-node1
Tm_Url:  192.168.64.49:30853
Enode_Url: "enode://e6ccd013b90e17ea7692905609f2a8a7922d855ebcb4476f1afc6aa4ad4261a2af40df9f1b6f4c6a83c96fd40bbad4d63352047d890a278d6cd410a225a1a236@192.168.64.49:31500?discport=0&raftport=50401"
Node_Acct_Addr: "0xC7868aA6C261aAaDA3E370315B6CF752056F54d1"
- Node_UserIdent:  quorum-node2
Tm_Url:  192.168.64.49:31680
```
This is the information that a cluster needs to …
> Basic multi-cluster support

- qctl/configcmd.go
- qctl/configyaml.go
- qctl/nodecmd.go
- templates/k8s/quorum-deployment.yaml.erb
- templates/k8s/quorum-keystore.yaml.erb
- templates/k8s/quorum-shared-config.yaml.erb
- templates/quorum/gen-keys.sh.erb
- templates/quorum/genesis.json.erb
* a Quorum qibft branch must be built locally, or obtained from a docker repo.
* qubernetes docker image support added for generating compatible quorum
and k8s resources for qibft.
* qctl support for generating a qubernetes config to support qibft.
e.g. if branch quorum-updated_ibft image built locally:
qctl init --consensus=qibft --qimagefull=quorum-updated_ibft
see: https://github.com/ConsenSys/qubernetes/tree/master/qctl/local-dev
for building and running images locally.
> support for qibft consensus.

- qctl/configyaml.go
- qctl/networkcmd.go
- qctl/nodecmd.go
- qctl/qctl.go
- templates/quorum/istanbul-validator.toml.erb
* add external_nodes to configyaml used by qctl, so qctl can interact with it, 
e.g. add, delete, ls
* add support for listing the external nodes in a network:
> qctl ls extnodes --all
* add support for adding an external node:
> qctl add extnode --enode="enode://12343@1.2.3.4:7000" --tmurl=http://1.2.3.4:9000  --nodekeyaddr=0x1234334
*  add support deleting external nodes:
>  qctl delete external-node
* allow the external_node `Node_Acct_Addr` field to be set to a hex without quotes
or a string hex in the qubernetes yaml. If it is set as a hex without quotes, the hex value will 
be converted to a BigNum, cover both cases in `istanbul-validator.toml.erb`. 
the yaml parser (https://godoc.org/gopkg.in/yaml.v2) used does not preserve double 
quotes around the hex …
> [qctl] support external nodes

- qctl/nodecmd.go
- templates/quorum/istanbul-validator.toml.erb
when converting the nodekey addr from integer to hexidecimal, we need to
pad the hex with leading 0s to get a constant address length of 40 hex
chars.
> pad nodekey addr with 0s to get addr constant sz.

- qctl/networkcmd.go
- qctl/testcmd.go
- qctl/utils.go
Use the namespace flag or env var QUORUM_NAMESPACE (if set) when running
the `qctl test contract` command and the `qctl create network` command.
> [qctl] use namespace with network / test command.

- qctl/utils.go
Tessera port displayed when running qctl ls urls.
> qctl ls urls --type nodeport
This is the p2p tessera port and used to connect external-node and
obtaining partyinfo
curl http://K8s_NODE_IP:Node_Port/partyinfo
> [qctl] fix DefaultTesseraPort 9080 -> 9001.

- templates/k8s/quorum-shared-config.yaml.erb
- testing/test-k8s-resources.sh
- testing/test-qnet.sh
As per issue: https://github.com/ConsenSys/qubernetes/issues/99
single node deployments may be useful for testing, etc.
When setting up the private test contract, use the node key of node1
instead of node2 which does not exist in a single node deployment.
> qctl init --num 1
> qctl generate network --create
> qctl deploy network
> Allow single node deployments.

- dev/README.md
- dev/docker-helpers/Dockerfile.quorum
- dev/docker-helpers/Dockerfile.quorumbase
- dev/docker-helpers/quorum-build-all.sh
- dev/docker-helpers/quorum-build.sh
* documentation for building local images that are accessible via
minikube.
* example of running a mixed net (local images, and release).
> Add basic documentation for local dev with qctl.

- Dockerfile
- qctl/configcmd.go
- qctl/configyaml.go
- qctl/utils.go
- quorum-config
- templates/config/qubernetes-quickstart.yaml.erb
- templates/k8s/quorum-deployment.yaml.erb
- templates/k8s/quorum-keystore.yaml.erb
- templates/k8s/quorum-shared-config.yaml.erb
- templates/quorum/gen-keys.sh.erb
- templates/quorum/genesis.json.erb
- testing/qversions-config/qubes-qbft-21.7.1-tessera-21.7.2.yaml
`qbft` fork block has been updated to `testQBFTBlock`. `qctl` and `quick-start` has been updated to reflect the same. Also, `qbft` now uses `qbft` binary from `istanbul-tools` to encode validators
> Updating qbft fork block to testQBFTBlock and added test for qbft
